"""migrations for DaysToHireStat

Revision ID: bd3637bbb421
Revises: 991ecb2bf269
Create Date: 2025-05-18 18:36:59.275023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd3637bbb421'
down_revision = '991ecb2bf269'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_to_hire_stats',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('standard_job_id', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('avg_days_to_hire', sa.Float(), nullable=True),
    sa.Column('min_days_to_hire', sa.Float(), nullable=True),
    sa.Column('max_days_to_hire', sa.Float(), nullable=True),
    sa.Column('count_of_job_postings', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_days_to_hire_stats_country_code'), 'days_to_hire_stats', ['country_code'], unique=False, schema='public')
    op.create_index(op.f('ix_public_days_to_hire_stats_standard_job_id'), 'days_to_hire_stats', ['standard_job_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_days_to_hire_stats_standard_job_id'), table_name='days_to_hire_stats', schema='public')
    op.drop_index(op.f('ix_public_days_to_hire_stats_country_code'), table_name='days_to_hire_stats', schema='public')
    op.drop_table('days_to_hire_stats', schema='public')
    # ### end Alembic commands ###
